### ISSUE TITLE
无法浏览具体文件

### ISSUE THREAD

**Issue by xiaoye-2018** [bigsinger/adbgui#1]
1. 打开data目录是空的，是否是由于当前软件没有使用su 权限查看目录
![image](https://github.com/bigsinger/adbgui/assets/46118372/051673a6-8c3e-4ffb-95b2-adf2fa8873c2)
2. apk文件无法导出
![image](https://github.com/bigsinger/adbgui/assets/46118372/4556261f-c360-4c6a-992b-0ef097001bf5)

**Comment by bigsinger** [comment]
> 1. 打开data目录是空的，是否是由于当前软件没有使用su 权限查看目录
>    ![image](https://private-user-images.githubusercontent.com/46118372/287281700-051673a6-8c3e-4ffb-95b2-adf2fa8873c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjE4MjYsIm5iZiI6MTcwMTY2MTUyNiwicGF0aCI6Ii80NjExODM3Mi8yODcyODE3MDAtMDUxNjczYTYtOGMzZS00ZmZiLTk1YjItYWRmMmZhODg3M2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDAzNDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MmYyOTBhYzU3MzdkNzkwZWZiY2M0YWRjZGE1ZWM5YTRmOWY3YmI1NTM3NjE0YzNjMmUwN2U2MmE4NDkzNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qiDIRWfoFnJUIv-iwqkLh6viSzEMC6nQbeZc3wjbDIw)
> 2. apk文件无法导出
>    ![image](https://private-user-images.githubusercontent.com/46118372/287282123-4556261f-c360-4c6a-992b-0ef097001bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjE4MjYsIm5iZiI6MTcwMTY2MTUyNiwicGF0aCI6Ii80NjExODM3Mi8yODcyODIxMjMtNDU1NjI2MWYtYzM2MC00YzZhLTk5MmItMGVmMDk3MDAxYmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDAzNDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MWY0ZjFmN2JjNWRmNWI2NGNlODI2YmQ1MzkzZDUzYWIxYWE3ZDZlMjRjOGY1NDAzOTM4MzA4NTJjMGJmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JEZbxEjpr7cRy2P65eHVCVbF92A5hU__zr4XAvMDvuQ)

root了吗
