### ISSUE TITLE
怎么切换为root权限，

### ISSUE THREAD

**Issue by G-YA123** [bigsinger/adbgui#4]
我在adb shell命令行中执行adb root，显示报错

**Comment by bigsinger** [comment]
错误信息是啥

**Comment by G-YA123** [comment]
![1](https://github.com/user-attachments/assets/ae2dfa84-6188-4348-a3a2-01e1f426afa0)
师傅，麻烦看看

**Comment by G-YA123** [comment]
![2](https://github.com/user-attachments/assets/749045d3-2412-4103-8694-29fa32294473)
麻烦师傅看看

**Comment by bigsinger** [comment]
不要带：adb

**Comment by G-YA123** [comment]
![1](https://github.com/user-attachments/assets/d72cd2c7-77c8-46f5-a0d5-b98be01b54dc)
![2](https://github.com/user-attachments/assets/e2774393-deb1-44e1-842d-138a6949262a)
单独执行root命令，还是无法提升权限

**Comment by bigsinger** [comment]
要先root设备，这个软件只是方便操作的一个工具，并不能直接root手机设备。

**Comment by G-YA123** [comment]
好嘞，多谢师傅
